//! The table as a C header: `static const` tables and the `CHDEF_LAYOUT`
//! the core's C entry points take.
//!
//! Fields are written positionally, in the order
//! `crates/chdef-core/include/chdef_core.h` declares them — a designated
//! initialiser would name `default`, which C cannot.

use chdef_core::Endian;

use crate::Model;

/// The table as a C header. `origin` says where it came from, for the
/// reader who finds the file and wonders.
pub fn c_header(model: &Model, origin: &str) -> String {
    let mut out = format!("/* Generated by chdef-gen from {origin}. Do not edit; regenerate. */\n");
    out.push_str("\n#ifndef CHDEF_LAYOUT_H\n#define CHDEF_LAYOUT_H\n\n");
    out.push_str("#include \"chdef_core.h\"\n");
    // C has no empty initialiser list, so an absent table is a null
    // pointer and a count of zero — and NULL needs a header of its own.
    if model.slots.is_empty() || model.derived.is_empty() {
        out.push_str("#include <stddef.h>\n");
    }

    out.push_str(&format!("\n#define CHDEF_TOTAL_BYTES {}\n", model.total));
    if !model.names.is_empty() {
        out.push('\n');
    }
    for (number, name) in &model.names {
        out.push_str(&format!("#define CHDEF_CH_{name} {number}\n"));
    }

    if !model.slots.is_empty() {
        out.push_str("\nstatic const ChdefCoreSlot CHDEF_SLOTS[] = {\n");
        for slot in &model.slots {
            out.push_str(&format!(
                "    {{{}u, {}u, {}u, 0x{:X}ull}},\n",
                slot.number, slot.at, slot.bytes, slot.default
            ));
        }
        out.push_str("};\n");
    }

    for (index, derived) in model.derived.iter().enumerate() {
        out.push_str(&format!(
            "\nstatic const ChdefCoreRange CHDEF_COVERS_{index}[] = {{\n"
        ));
        for range in &derived.covers {
            out.push_str(&format!("    {{{}u, {}u}},\n", range.at, range.len));
        }
        out.push_str("};\n");
    }

    if !model.derived.is_empty() {
        out.push_str("\nstatic const ChdefCoreDerived CHDEF_DERIVED[] = {\n");
        for (index, derived) in model.derived.iter().enumerate() {
            let crc = derived.crc;
            out.push_str(&format!(
                "    {{{}u, {{{}u, 0x{:X}ull, 0x{:X}ull, {}, {}, 0x{:X}ull}}, CHDEF_COVERS_{index}, {}u}},\n",
                derived.slot,
                crc.width,
                crc.poly,
                crc.init,
                crc.refin,
                crc.refout,
                crc.xorout,
                derived.covers.len()
            ));
        }
        out.push_str("};\n");
    }

    let slots = table("CHDEF_SLOTS", model.slots.len());
    let derived = table("CHDEF_DERIVED", model.derived.len());
    let endian = match model.endian {
        Endian::Little => "CHDEF_CORE_LITTLE",
        Endian::Big => "CHDEF_CORE_BIG",
    };
    out.push_str(&format!(
        "\nstatic const ChdefCoreLayout CHDEF_LAYOUT = {{ {slots}, {derived}, {endian}, {}u }};\n",
        model.total
    ));

    out.push_str("\n#endif /* CHDEF_LAYOUT_H */\n");
    out
}

/// A table and its count, as the layout names them; an empty one is the
/// null pointer C leaves for it.
fn table(name: &str, count: usize) -> String {
    if count == 0 {
        "NULL, 0u".to_string()
    } else {
        format!("{name}, {count}u")
    }
}
