//! The table as Rust source: a `LAYOUT` constant the core's own calls
//! take, and one `CH_…` constant per named channel.
//!
//! The file is written in the shape `rustfmt` would leave it in, so a
//! firmware tree that checks its formatting does not have to exempt what
//! the generator wrote.

use chdef_core::{Endian, Range, Slot};

use crate::{DerivedModel, Model};

/// `rustfmt`'s default `max_width`: the column a line may not pass.
const WIDTH: usize = 100;

/// `rustfmt`'s default `array_width`: how wide `[…]` may be, brackets
/// counted, before every element takes a line of its own. Measured on the
/// literal and not on the line, so where it sits does not enter into it.
const ARRAY_WIDTH: usize = 60;

/// The table as a Rust source file. `origin` says where it came from, for
/// the reader who finds the file and wonders.
pub fn rust_source(model: &Model, origin: &str) -> String {
    let mut out = format!("// Generated by chdef-gen from {origin}. Do not edit; regenerate.\n");
    out.push_str("#[allow(unused_imports)]\n");
    out.push_str("use chdef_core::{Crc, Derived, Endian, Layout, Range, Slot};\n");

    for (number, name) in &model.names {
        out.push_str(&format!("\n/// Channel `{}`.\n", name.to_lowercase()));
        out.push_str(&format!("pub const CH_{name}: u32 = {number};\n"));
    }

    out.push_str("\npub const LAYOUT: Layout<'static> = Layout {\n");
    let slots: Vec<Vec<String>> = model.slots.iter().map(slot_literal).collect();
    push_array(&mut out, "slots", 4, 4, &slots);
    push_derived(&mut out, &model.derived);
    out.push_str(match model.endian {
        Endian::Little => "    endian: Endian::Little,\n",
        Endian::Big => "    endian: Endian::Big,\n",
    });
    out.push_str(&format!("    total: {},\n", model.total));
    out.push_str("};\n");
    out
}

/// The `derived` field, whose elements hold an array of their own: how the
/// outer one breaks decides the column the inner one is measured at.
fn push_derived(out: &mut String, derived: &[DerivedModel]) {
    let base = if derived.len() == 1 { 4 } else { 8 };
    let elements: Vec<Vec<String>> = derived.iter().map(|d| derived_literal(d, base)).collect();
    push_array(out, "derived", 4, 4, &elements);
}

/// One `field: &[…]` in the shape `rustfmt` gives it: on one line where it
/// fits, a lone multi-line element overflowed into the brackets, and one
/// element per line otherwise.
///
/// `indent` is where the field is written and `column` where it ends up —
/// the two differ for an array nested inside a literal that is itself
/// indented later. Element lines are relative to the element's own first
/// line, which carries no indent of its own.
fn push_array(
    out: &mut String,
    field: &str,
    indent: usize,
    column: usize,
    elements: &[Vec<String>],
) {
    let pad = " ".repeat(indent);
    let inner = " ".repeat(indent + 4);

    if elements.is_empty() {
        out.push_str(&format!("{pad}{field}: &[],\n"));
        return;
    }

    if elements.iter().all(|lines| lines.len() == 1) {
        let joined: Vec<&str> = elements.iter().map(|lines| lines[0].as_str()).collect();
        let literal = joined.join(", ");
        let one = format!("{pad}{field}: &[{literal}],");
        if literal.len() + 2 <= ARRAY_WIDTH && one.len() + column - indent <= WIDTH {
            out.push_str(&one);
            out.push('\n');
            return;
        }
        out.push_str(&format!("{pad}{field}: &[\n"));
        for lines in elements {
            out.push_str(&format!("{inner}{},\n", lines[0]));
        }
        out.push_str(&format!("{pad}],\n"));
        return;
    }

    if let [lines] = elements {
        let (first, rest) = lines.split_first().expect("a literal has a first line");
        let (last, middle) = rest
            .split_last()
            .expect("a multi-line literal has a closer");
        out.push_str(&format!("{pad}{field}: &[{first}\n"));
        for line in middle {
            out.push_str(&format!("{pad}{line}\n"));
        }
        out.push_str(&format!("{pad}{last}],\n"));
        return;
    }

    out.push_str(&format!("{pad}{field}: &[\n"));
    for lines in elements {
        for (index, line) in lines.iter().enumerate() {
            let comma = if index + 1 == lines.len() { "," } else { "" };
            out.push_str(&format!("{inner}{line}{comma}\n"));
        }
    }
    out.push_str(&format!("{pad}],\n"));
}

/// A `Slot` literal. Its body passes `rustfmt`'s `struct_lit_width` at
/// every value, so it is always written out one field per line.
fn slot_literal(slot: &Slot) -> Vec<String> {
    vec![
        "Slot {".to_string(),
        format!("    number: {},", slot.number),
        format!("    at: {},", slot.at),
        format!("    bytes: {},", slot.bytes),
        format!("    default: 0x{:X},", slot.default),
        "}".to_string(),
    ]
}

/// A `Derived` literal, written to sit `base` columns in.
fn derived_literal(derived: &DerivedModel, base: usize) -> Vec<String> {
    let crc = derived.crc;
    let mut lines = vec![
        "Derived {".to_string(),
        format!("    slot: {},", derived.slot),
        "    crc: Crc {".to_string(),
        format!("        width: {},", crc.width),
        format!("        poly: 0x{:X},", crc.poly),
        format!("        init: 0x{:X},", crc.init),
        format!("        refin: {},", crc.refin),
        format!("        refout: {},", crc.refout),
        format!("        xorout: 0x{:X},", crc.xorout),
        "    },".to_string(),
    ];
    let covers: Vec<Vec<String>> = derived.covers.iter().map(range_literal).collect();
    let mut written = String::new();
    push_array(&mut written, "covers", 4, base + 4, &covers);
    lines.extend(written.lines().map(str::to_string));
    lines.push("}".to_string());
    lines
}

/// A `Range` literal, on one line while its body stays inside
/// `rustfmt`'s `struct_lit_width`.
fn range_literal(range: &Range) -> Vec<String> {
    let body = format!("at: {}, len: {}", range.at, range.len);
    if body.len() <= 18 {
        return vec![format!("Range {{ {body} }}")];
    }
    vec![
        "Range {".to_string(),
        format!("    at: {},", range.at),
        format!("    len: {},", range.len),
        "}".to_string(),
    ]
}
